### ISSUE TITLE
View für erfolgreichen Checkin

### ISSUE THREAD

**Issue by clueckler** [Didi71/BIKELine_old_tbd#1]
Die grafische Umsetzung des CheckIn-Views (QR-Reader) und des View's bei erfolgreichem scannen müsste noch gemacht werden.

**Comment by starflower** [comment]
Lass uns das zusammen am Donnerstag machen :)

**Comment by clueckler** [comment]
Genau deswegen hab ich dich ja gefragt, wann du in der Firma bist ;-)

**Comment by clueckler** [comment]
Drafts liegen unter https://www.dropbox.com/home/BIKEline/iOS
