### ISSUE TITLE
Mehrere View's updaten und Funktionen hinzufügen

### ISSUE THREAD

**Issue by clueckler** [Didi71/BIKELine_old_tbd#13]
Nachdem die Spezifikation für iPhone geändert wurde müssen einige View's angepasst werden. Jeder Draft muss mit dem dazugehörigen View verglichen und upgedated werden.

Zeitschätzung: 1-2 Arbeitstage (8-16h)

**Comment by clueckler** [comment]
@starflower wie soll der Info-View aussehen??

**Comment by starflower** [comment]
Ist jetzt in der Dropbox. Ist laut meinem Wissen nur Text mit einem Link am Ende.

**Comment by Didi71** [comment]
ja!

Am 10.09.2013 22:35, schrieb Matthias Kampitsch:
