### ISSUE TITLE
Facts - Team beitraten

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine_old_tbd#15]
Am Screen bei dem das Team ausgewählt werden kann wird der erklärende Text nicht vollständig angezeigt. Es endet mit: Wenn du dich einem Team anschließt, ...

**Comment by clueckler** [comment]
So ein langer Text war im ersten Draft nicht drinnen.
Wenn sich das Textfeld dynamisch der länge des Text's anpassen soll muss dies implementiert werden (Kein BUG).

Zeitaufwand: 2-3h
