### ISSUE TITLE
Team Screen - Headline

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine_old_tbd#16]
Wenn man einem Team beigetreten ist, dann sollte als Headline folgende Zeilen zentriert ausgegeben werden:

Überschrift Fett:     Team <vorname> <nachname>
Normal:                 aus <city> - XY BIKEbirds

XY = alle BIKEbirds die das Team bereits gesammelt hat.

**Comment by clueckler** [comment]
Bug?? .... Wird auf jeden Fall mal als Feature gekennzeichnet, da dies nicht spezifiziert war.
Was meinst du mit Headline??

**Comment by Didi71** [comment]
Naja ganz oben am Screen sollte ausgegeben werden für welches Team man eigentlich fährt.
