### ISSUE TITLE
Team/Preise Screen - horizontale Linien

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine_old_tbd#17]
Horizontale Linien sollten nur zwischen Einträgen ausgegeben werden.

**Comment by clueckler** [comment]
Nicht üblich unter iOS. Müsste explizit implementiert werden und wurde so nicht spezifiziert!

Zeitaufwand ca. 2h

**Comment by Didi71** [comment]
Ja, mach das bitte, wenn mal eine ruhige Stunde ist.
