### ISSUE TITLE
CheckPoints - Sceen : Zoom 

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine_old_tbd#21]
gibt's für's iPhone +/- zoom-Buttons zum Rein/Rauszoomen?
Wäre toll.

**Comment by clueckler** [comment]
Unter iOS nicht üblich!

**Comment by Didi71** [comment]
Wär aber trotzdem zweckmäßig - wenn's geht, dann sollten wir das machen.

**Comment by clueckler** [comment]
Najo zweckmäßig? Ich kenn keine iOS App mit Map die diese Icons anzeigt? Man arbeitet unter iOS mit der Gestensteuerung. Wenn es aber gewünscht wird, dann musst du @starflower um einen Draft bitten!

**Comment by Didi71** [comment]
na dann lass uns bei der Gestensteuerung bleiben
