### ISSUE TITLE
CheckPoints - Icons

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine_old_tbd#23]
Als Symbole für die Marker bitte die von Matthias vorgesehenen Icons verwenden.

CheckPoints die hot sind, werden orange dargestellt.

**Comment by clueckler** [comment]
Wurde nicht so spezifiziert.

Zeitaufwand: 2h

**Comment by Didi71** [comment]
in der 10-map.png sind die Icons verwendet - Matthias könntest du bitte sicherstellen, dass sie auch als Ressourcen zur Verfügung stehen.
