### ISSUE TITLE
CheckPoint - Infobox

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine_old_tbd#25]
Wenn man auf einen CheckPoint tippt, dann wir ein Infofenster angezeigt.

Die Überschrift des CheckPoints sollte der Name des CheckPoints sein 
z.B. 

Buschenschank Knöbl

Wenn es zu diesem CheckPoint ein Event gibt, dann sollten darunter Infos zum Event angezeigt werden z.B.
## Buschenschank Knöbl

Kaindorfer Radherbst
28.08. - 30.10.2013

**Comment by clueckler** [comment]
Die Annotations in Maps sind nur Zweizeilig!
Mehrzeilige Annotations sind nicht möglich bzw. die Umsetzung von diesen würde ca. 8h in Anspruch nehmen!
