### ISSUE TITLE
CheckPoint - Infobox mit Link

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine_old_tbd#26]
Wenn für den CheckPoint eine Webpage hinterlegt ist, dann sollte neben dem Namen des CheckPoints ein ">" angezeigt werden um beim Klicken auf dieses Symbol auf die Webpage weitergeleitet zu werden. z.B. 

Buschenschank Knöbl    >

Wenn für den CheckPoint ein Event mit einer Webpage hinterlegt ist, sollte auch ein ">" angezeigt werden z.B.
## Buschenschank Knöbl

Kaindorfer Radfrühlung    >
28.08. - 30.10.2013

Wenn sowohl für den CheckPoint als auch für das Event eine Webpage hinterlegt ist, so wird die vorherige Infobox angezeigt, und beim Drücken auf ">" eine Auswahlfenster angezeigt:
# Öffne Webpage ...
## Buschenschank Knöbl

Kaindorfer Radfrühling

**Comment by clueckler** [comment]
Nicht spezifiziert ....

Zeitaufwand: 4h
