### ISSUE TITLE
Facts - Screen

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine_old_tbd#27]
Mir scheint, als würde nicht die korrekte Anzahl von BIKEbirds und der aktuelle Rang angezeigt, wenn man sich via "Bereits Mitglied?" anmeldet.

**Comment by clueckler** [comment]
Wie auch ... es gibt keinen Request.
Zuerst müssen die Checkins geladen werden und dann wied der view aktualisiert!

**Comment by Didi71** [comment]
oha - dar war ein Bug in der Wiki-Beschreibung.
der Request heisst - getCheckInInfo.php

**Comment by clueckler** [comment]
Alles klar, wird implementiert und auf "Enhancement" geändert
