### ISSUE TITLE
Eingechecked Screen - Werte

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine_old_tbd#29]
Beim Eingechecked-Screen werden falsche Werte angezeigt.

im kleine Kreis sollte stehen: + bikebirds-bikebirdsOld
im linken Kreis: bikebirds
im rechten Kreis: rank.

**Comment by clueckler** [comment]
Es werden hier die Werte angezeigt, die du mir zurückgibtst. Wenn diese bereits falsch sind, dann sollten die Server Responses angepasst werden!

**Comment by Didi71** [comment]
welche werte aus der response zeigst du an?

im kleine Kreis sollte stehen: + bikebirds-bikebirdsOld
im linken Kreis: bikebirds
im rechten Kreis: rank.

**Comment by clueckler** [comment]
Fehler von mir, die gewonnenen BikeBirds wurden nicht in das Feld eingetragen!

**Comment by clueckler** [comment]
Berechnung der gewonnenen Bikebirds auf "bikebirdsOld + bikebirds" ändern (siehe #30)!
