### ISSUE TITLE
CheckIns - Liste

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine_old_tbd#30]
Die Liste der CheckIns wird nicht angezeigt

**Comment by clueckler** [comment]
Es wird genau das angezeigt, was vom Server zurückkommt ....

**Comment by Didi71** [comment]
Das ist komisch, weil die Android App da was anzeigt.
Übergibst du die bikerId ?

**Comment by clueckler** [comment]
Jup gebe ich mit, hier mal mein request dump (Zuerst checkin):

> 2013-09-16 19:36:42.609 bikeline-ios-test[312:4107] -[BBApiAbstractOperation main] (33) 
>     URL = http:/www.bikebird.at/BIKElineCheckPoint/TestApp-Scripts/checkIn.php
> 2013-09-16 19:36:42.610 bikeline-ios-test[312:4107] -[BBApiAbstractOperation main] (34) 
>     PARAMETERS = {
>     APIKey = motPFm2n8E3N5FdGIK4H;
>     PIN = 73322;
>     bikerId = 16;
>     checkPointId = 13432022;
>     teamId = 27812;
> }
> 2013-09-16 19:36:42.953 bikeline-ios-test[312:4107] -[BBApiAbstractOperation main] (64) 
>     RESPONSE = {
>     bikebirds = 1;
>     bikebirdsFirstCheckIn = 0;
>     bikebirdsFirstCheckPointCheckIn = 0;
>     bikebirdsOld = 32;
>     checkPointCity = Kaindorf;
>     checkPointName = "Gasthof Pension Steinbauer";
>     date = 1379353002000;
>     errorCode = 0;
>     price =     {
>         description = "eine Brettljause von";
>         eventName = "Kaindorfer Radfr\U00fchling";
>         sponsorCity = Kaindorf;
>         sponsorName = "Buschenschank Schmalegger";
>         timeWon = 0;
>     };
>     priceText = "Du hast gerade eine Brettljause vom Buschenschank Kn\U00f6bl gewonnen.";
>     rank = 1;
> }
> 2013-09-16 19:37:11.125 bikeline-ios-test[312:df07] -[BBApiAbstractOperation main] (33) 
>     URL = http:/www.bikebird.at/BIKElineCheckPoint/TestApp-Scripts/getCheckIns.php
> 2013-09-16 19:37:11.126 bikeline-ios-test[312:df07] -[BBApiAbstractOperation main] (34) 
>     PARAMETERS = {
>     APIKey = motPFm2n8E3N5FdGIK4H;
>     PIN = 73322;
>     bikerId = 16;
> }
> 2013-09-16 19:37:11.401 bikeline-ios-test[312:df07] -[BBApiAbstractOperation main] (64) 
>     RESPONSE = {
>     checkIns =     (
>     );
>     errorCode = 0;
> }

**Comment by Didi71** [comment]
auf verd...t - ich kenn meine eigenen Skripts nicht mehr.

bikebirds gibt an wieviele BIKEbirds der User bei diesem CheckIn 
gesammelt hat.
Die neue Anzahl errechnet sich somit aus bikebirdsOld + bikebirds.

Am 16.09.2013 19:41, schrieb Christoph Lückler:

**Comment by clueckler** [comment]
@Didi71 .... Falsches Ticket?? Das gehört wohl zu #29

**Comment by Didi71** [comment]
stimmt das ist #29
