### ISSUE TITLE
Hauptmenü unten.

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine_old_tbd#31]
Da sollte es lt. Matthias neue Anzeigen geben, wenn ein Feld gewählt ist.

Wenn z.B. die CheckPoints gewählt sind, dann sollte das CheckPoint Zeichen türkis hinterlegt sind.

Wenn CheckIn gewählt ist, dann der QR-Code, und wenn Facts angezeigt werden sollte das Icon mit den 3 Strichen türkis sein.

**Comment by clueckler** [comment]
Gibt es noch keine Ressourcen in der Dropbox. 
@starflower bitte bereitstellen!

**Comment by starflower** [comment]
Eye, Eye, Captain! Sind schon seit einer Woche in der Dropbox :) Ordner nennt sich Tabbar-new ;)

**Comment by clueckler** [comment]
Ach herjemine ... Kannst nit einfach de alten dinger überschreiben? DP hat eh version control ;-)

**Comment by starflower** [comment]
Bin ein Fan von dateiname-new-final-NEW-FINALVERSION-3.psd :D
