### ISSUE TITLE
Scannen

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine_old_tbd#32]
Beim Scannen brauchen wir mehr User Feedback.

Wenn ein QR-Code richtig erkannt wurde, dann sollte das Hintergrundbild eingefroren werden und folgender Toast angezeigt werden:

<fortschrittsicon> CheckIn läuft ...

Wenn möglich, dann sollte bei einem gescannten QR-Code das Handy auch vibrieren.

**Comment by clueckler** [comment]
Einfrieren ist durch das verwendete QR-Framework nicht möglich!
Vibration kann erfolgen.
