### ISSUE TITLE
Show Info - Menü

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine_old_tbd#35]
umbenennen in: Allgemeine Infos

Allgemeine Infos sollte der erste Menüeintrag sein

**Comment by clueckler** [comment]
Bitte Tickets die Zusammenhängen (Wie die Anzeige der Icons und Umbenennen von Icons) als EIN  Ticket anlegen. Sonst kennt man sich ja überhaupt nicht mehr aus!
