### ISSUE TITLE
Abmelden - Menü

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine_old_tbd#37]
Warum ist eigentlich der Abmelden Button rot, und nicht so wie die anderen hellgrau?

**Comment by starflower** [comment]
1. Rot = In unseren Kulturkreisen "Gefahr". D.h. gefährliche Aktion = vermeiden.
2. Damit das im ActionSheet Menü nicht untergeht und nicht "versehentlich" passiert.
3. Weil das eine Nutzerfahrung ist, die die User von allen anderen Apps gewohnt sein dürften.

**Comment by Didi71** [comment]
na dann lass ma's so - (für mich persönlich ist sowas markant-rotes eher was zum Draufdrücken.)
