### ISSUE TITLE
QR-Code gelesen - CheckIn Message

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine_old_tbd#39]
Wenn der QR-Code gelesen wurde, dann sollte ein Infobox angezeigt werden:

CheckIn läuft ...

**Comment by clueckler** [comment]
Es wird bereits progressCheckInTitle (= CheckIn läuft ...) angezeigt. Wenn Requests so schnell durchgehen, dann ist das halt nicht sichtbar. Man könnte das ausblenden nur verzögern um diesen ProgressHud sichtbar zu machen.

Frage ist aber, was soll passieren, wenn man eine schlechte Internetverbindung hat .... Also einfach verlängern geht da auch nicht. Dazu muss man sich mehr Gedanken machen!

**Comment by Didi71** [comment]
Es dauert relativ lang zwischen dem Vibrieren (=QR-Code erkannt) und der 
Anzeige der CheckIn-Infos. Auch dass während dieser Zeit die Kamera noch 
aktiv ist, ist verwirrend.

In der Android Applikation wird sobald der QR-Code erkannt wurde das 
Bild eingefroren (das gibt aber das iOS Framework nicht her) und bis zur 
Anzeige der CheckIn-Infos die Message "CheckIn läuft ..." angezeigt. Der 
User weiss somit immer was Sache ist.

Könnte man nicht die Anzeige der Message verlänger, bis auch der 
CheckIn-InfoScreen angezeigt wird?

Am 16.09.2013 21:12, schrieb Christoph Lückler:
