### ISSUE TITLE
Text ändern

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine_old_tbd#41]
editBikerInfoTeaserText = Hier kannst du dein Profil bearbeiten
Edit Info = Profil bearbeiten
New Photo = Foto aufnehmen

Im Profil bearbeiten Screen den "Ändern" Button umbenennen in "Speichern" und ganz unten anzeigen.

Change user info ...  umbenennen in  Profil speichern ...
Change successfull ... umbenennen in Profil gespeichert!

**Comment by clueckler** [comment]
Ich würde den Button nicht ganz nach unten tun. 
Würde die ganze Logik des im Hintergrund befindlichen ScrollView's zerstören. Weiters müsste der Nutzer umsonst ziemlich weit nach unten scrollen!

**Comment by Didi71** [comment]
Da ist ja nix zu scrollen! Der Button sollte, so wie auch die "Weiter" 
Buttons, am unteren Rand des Screens dargestellt werden.

Am 16.09.2013 21:36, schrieb Christoph Lückler:

**Comment by clueckler** [comment]
Wenn du in ein Feld klickst, dann wirst du merken, dass das Keyboard die Zellen überlagert (gleich wie bei der Registrierung) und deshalb ist der ScrollView von nöten!

![screenshot 2013 09 16 21 42 09](https://f.cloud.github.com/assets/2933522/1152192/33425e66-1f08-11e3-8ff0-4e28485a3c13.png)

**Comment by Didi71** [comment]
du hast recht - lass ma's wie's is - macht Sinn. nur bitte das Ändern in 
Speichern umbenennen.

Am 16.09.2013 21:43, schrieb Christoph Lückler:

**Comment by clueckler** [comment]
Ah stimmt, das hab ich beim commit noch vergessen ... wird gemacht!
