### ISSUE TITLE
Navbar SegmentControl Breite

### ISSUE THREAD

**Issue by starflower** [Didi71/BIKELine_old_tbd#8]
Bitte das Segmented Control verbreitern, so dass es 10dp links und rechts Abstand vom Displayrand hat.

**Comment by clueckler** [comment]
Najo ob das so sinnvoll ist stell ich nun mal in den Raum, da die Breite ja automatisch vom iOS berechnet wird.

**Comment by starflower** [comment]
Oh ok, dachte du kannst das einstellen, weil die mittleren breiter sind als die äußeren.

**Comment by starflower** [comment]
Kannst Du da bitte nochmal kurz draufschaun? Irgendwie wirken die Linien verpixelt. Danke!!!
